### ISSUE TITLE
build and publish release in TravisCI pipeline

### ISSUE THREAD

**Issue by cheyilin** [tsunejui/fops#3]
Please integrate build process into TravisCI with version tagging for #2, and also publish a release automatically with built executable.

**Comment by tsunejui** [comment]
@CheyiLin 
I have updated the code, the application version is no longer a hard-coded value, and TravisCI will be able to publish a release automatically with built executable.

**Comment by cheyilin** [comment]
Verified, will close #2 as well. Thank you.
