### ISSUE TITLE
try doing blackbox test by using separate test package

### ISSUE THREAD

**Issue by cheyilin** [tsunejui/fops#4]
Try blackbox testing your packages by simply adding suffix `_test` to testing package name eg.

```diff
- package linecount
+ package linecount_test
```

Then modify tests to use exported APIs only without losing coverage rate.

**Comment by cheyilin** [comment]
Hi @tsunejui,

Nice to see you keep the original whitebox tests you implemented alongside the new blackbox tests. The latest release CI result [tsunejui/fops@travis-ci/v0.0.3](https://travis-ci.com/github/tsunejui/fops/builds/160732235) shows you achieved a decent test coverage.

Now all issues have been solved! 🎉🎉🎉
Thank you for all your hard work for this tiny toy project, hope you enjoyed it.

See you soon!

**Comment by tsunejui** [comment]
@CheyiLin 
Thank you for spending time on reviewing my codes too, I really appreciate it.
