### ISSUE TITLE
use cobra.Command's hook RunE to simplify the error handling

### ISSUE THREAD

**Issue by cheyilin** [tsunejui/fops#7]
cobra has a hook `RunE func(cmd *Command, args []string) error` returns error that the command handler returns. Try using this hook to simplify the cascading error/exception handling from subcommands to the top-level root command.

**Comment by tsunejui** [comment]
roger that

**Comment by tsunejui** [comment]
@CheyiLin 

Excuse me sir,
I’m not really sure if I get the question right, can you please take a look at branch `feature-7` and see if I have met your requirements. Thank you

**Comment by cheyilin** [comment]
I mean, you should **ONLY** return errors in all sub-commands' `RunE` without directly logging things, and handle errors (and log them) return from root command's `Execute()` all together.

That's what I said 'cascading error handling'.

**Comment by tsunejui** [comment]
@CheyiLin 

Got it, and I have fixed the issue.  Thank you for the explanation.

Please let me know if there's anything else I'm missing out

**Comment by cheyilin** [comment]
Thanks for the work, I left a review comment in #14, please take a look.

**Comment by cheyilin** [comment]
Saw the fix in commit 28c37e44f1015f65b9a66d780bb520fcc4788d07, thanks for your patience and hard work!
