### ISSUE TITLE
refine code structure

### ISSUE THREAD

**Issue by cheyilin** [tsunejui/fops#9]
It seems to me that the directory `src` should contain source code (ie. .go files) only, and independent packages should be sub-directories of `pkg`.

So please refine these:

- [x] Rename `src` > `docs` and update the links in `README` (use relative link path in the same repo)
- [x] Move packages (except `cmd`) into directory `pkg`

**Comment by tsunejui** [comment]
Hi @CheyiLin ,

I have refined the code structure, please take a look and let me know if there’s any problems. Thank you.

**Comment by tsunejui** [comment]
Hi @CheyiLin ,

I have refined the code structure, please take a look and let me know if there’s any problem. Thank you

**Comment by cheyilin** [comment]
Verified, thanks for your work!
